[package]
name = "rust_dealer"
version = "0.1.0"
authors = ["brianboyko <brian.boyko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.2.0"
